### ISSUE TITLE
I can't display this file in the delivery slip pdf.

### ISSUE THREAD

**Issue by dimijazz** [Mint-System/Odoo-Apps-Product-Attribute#1]
i added this code to the report but with no luck
<table class="table table-sm" t-if="o.state!='done'" name="stock_move_table">
                        <thead>
                            <tr>
                                <th name="th_sm_product"><strong>Product</strong></th>
                                <th name="th_sm_quantity"><strong>Quantity</strong></th>
                               <th name="th_sm_quantity"><strong>Country</strong></th>
                               
                                
                            </tr>
                        </thead>
                        <tbody>
                            <t t-set="lines" t-value=" x: x.product_uom_qty)"/>
                            <tr t-foreach="lines" t-as="move">
                                <td>
                                    <span t-field="move.product_id"/>
                                    <p t-if="move.description_picking != 
                                        <span t-field="move.description_picking"/>
                                    </p>
                                </td>
                                <td>
                                    <span t-field="move.product_uom_qty"/>
                                    <span t-field="move.product_uom"/>
                                </td>
                                <td>
                                  
                                    <span <span t-esc="move.country_of_origin_id"/>  
                                </td>

**Comment by janikvonrotz** [comment]
@dimijazz Here is an example: https://odoo.build/snippets.html#product-hs-code-and-origin
